package enums;

public enum RelicSet {
	BAND_OF_SIZZLING_THUNDER,
	CHAMPION_OF_STREETWISE_BOXING,
	EAGLE_OF_TWILIGHT_LINE,
	FIRESMITH_OF_LAVA_FORGING,
	GENIUS_OF_BRILLIANT_STARS,
	GUARD_OF_WUTHERING_SNOW,
	HUNTER_OF_GLACIAL_FOREST,
	KNIGHT_OF_PURITY_PALACE,
	LONGEVIOUS_DISCIPLE,
	MESSENGER_TRAVERSING_HACKERSPACE,
	MUSKETEER_OF_WILD_WHEAT,
	PASSERBY_OF_WANDERING_CLOUD,
	THIEF_OF_SHOOTING_METEOR,
	WASTELANDER_OF_BANDITRY_DESERT
}
